[package]
name    = "kestrel-serial-agent-lib"
version = "0.0.0" # ensure in sync with kestrel-serial-agent

authors.workspace      = true
edition.workspace      = true
publish.workspace      = true
repository.workspace   = true
rust-version.workspace = true

[dependencies]
