pub const MONOSPACE_CHAR_WIDTH: f32 = 7.0;

pub const TIMESTAMP_WIDTH: f32 = MONOSPACE_CHAR_WIDTH * 10.0;
pub const METRIC_NAME_WIDTH: f32 = MONOSPACE_CHAR_WIDTH * 20.0;
pub const METRIC_TYPE_WIDTH: f32 = MONOSPACE_CHAR_WIDTH * 7.0;
