name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt install -y libudev-dev
      - uses: swatinem/rust-cache@v2
      - name: Build
        run: cargo build --verbose --workspace
      - name: Test
        run: cargo test --verbose --workspace

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: swatinem/rust-cache@v2
      - name: Lint
        run: cargo clippy --verbose --workspace